In [5]:
import numpy as np

In [17]:
A = np.array([[1,2],[3,4]])
#matrix inverse with linalgebra inv method
Ainv = np.linalg.inv(A)
A



array([[1, 2],
       [3, 4]])

In [18]:
Ainv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [19]:
#we know that if we multipy a matrix with it's inverse we get Identitiy Matrix
Ainv.dot(A)

array([[1.0000000e+00, 4.4408921e-16],
       [0.0000000e+00, 1.0000000e+00]])

In [20]:
# Matrix determinat
np.linalg.det(A)

-2.0000000000000004

In [22]:
#diagonal of vector
np.diag(A)

array([1, 4])

In [23]:
#represent as 2-D Array 
np.diag([1,2])

array([[1, 0],
       [0, 2]])

# outer product / Inner Product

In [24]:
a = np.array([1,2])
b = np.array([3,4])

#outer product 
np.outer(a,b)

array([[3, 4],
       [6, 8]])

In [26]:
np.inner(a,b)
# or dot product 
#inner product is dot product

11

In [29]:
# Matrix Trace 
#sum of diagonal of matrix
np.diag(A).sum()
#or do the trace 
np.trace(A)

5

In [30]:
#Eigen Vectors or Eigen Values

x = np.random.randn(100,3)

In [32]:
cov = np.cov(x)

In [39]:
#covaraince Transpose is needed for right dimensions
#covaraiance of datamatrix to be transposed
cov = np.cov(x.T)
cov.shape

(3, 3)

# Eigen Vectors And Eigen Values


In [40]:
# eig method of np for eigen values or eigen vectors
# eig is symmetric and Hermitian matrices
# symmetric means A = A^T
# Hermitian means A = A^H
# A^H = conjugate Transpose of A

In [44]:
np.linalg.eig(cov)
#first tuple is eigen values 
# second tuples are eigen vectors

(array([1.19988265, 0.77957449, 0.85745523]),
 array([[ 0.98749477,  0.14967296,  0.04951856],
        [ 0.07285687, -0.15471514, -0.98526905],
        [ 0.13980687, -0.9765558 ,  0.16368509]]))