# Problem :  Ax = b
### Solution : A<sup>-1</sup> Ax = x = A<sup>-1</sup>
* Is a system of D equations and D unknowns
* A is D*D , assume it is invertible
* We have all the tools we need to solve this already 
* Matrix Inverse and 
* Matrix Multiply (dot)

In [24]:
import numpy as np

In [25]:
A = np.array([[1,2],[3,4]])
b = np.array([1,2])
A

array([[1, 2],
       [3, 4]])

In [26]:
Ainv = np.linalg.inv(A)
Ainv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [29]:
x = Ainv.dot(b)
x

array([2.22044605e-16, 5.00000000e-01])

In [28]:
x = np.linalg.solve(A,b)
x
# the point is always use solve method

array([0. , 0.5])